# Generated by Django 3.2.9 on 2021-11-10 18:51

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory_name',
        ),
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='product.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
